# Generated by Django 4.1.5 on 2023-03-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=100, verbose_name='عنوان در url'),
            preserve_default=False,
        ),
    ]
