# Generated by Django 4.1.5 on 2023-04-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'تصویر گالری', 'verbose_name_plural': 'تصاویر گالری'},
        ),
    ]
